version: 2

models:
  - name: fact_order_details
    description: "Fact table that stores detailed information about each order, including the products ordered, user details, and ordering behavior."
    columns:
      - name: order_id
        data_type: int64
        description: "Unique identifier for each order."

      - name: user_id
        data_type: int64
        description: "Unique identifier for the user who placed the order."

      - name: product_id
        data_type: int64
        description: "Unique identifier for each product in the order."

      - name: product_name
        data_type: string
        description: "The name of the product."

      - name: add_to_cart_order
        data_type: int64
        description: "The sequence in which the product was added to the cart during the order."

      - name: reordered
        data_type: int64
        description: "Indicates if the product was reordered (1 = yes, 0 = no)."

      - name: order_dow
        data_type: int64
        description: "Day of the week when the order was placed (0 = Sunday, 6 = Saturday)."

      - name: order_hour_of_day
        data_type: int64
        description: "Hour of the day (0-23) when the order was placed."

      - name: days_since_prior_order
        data_type: numeric
        description: "Number of days since the user's prior order."

      - name: aisle
        data_type: string
        description: "The aisle where the product is located."

      - name: department
        data_type: string
        description: "The department where the product belongs."

  - name: dim_aisles
    description: "Dimension table that contains data about aisles within the store, linking aisle names with their identifiers."
    columns:
      - name: aisle_id
        data_type: int64
        description: "Unique identifier for each aisle."

      - name: aisle
        data_type: string
        description: "Name of the aisle."

  - name: dim_order
    description: "Dimension table containing key information about orders, including the order time, user, and frequency of purchase."
    columns:
      - name: order_key
        data_type: string
        description: "Unique key for each order, used for primary referencing."

      - name: order_id
        data_type: int64
        description: "Unique identifier for each order."

      - name: user_id
        data_type: int64
        description: "Unique identifier for the user who placed the order."

      - name: order_dow
        data_type: int64
        description: "Day of the week when the order was placed (0 = Sunday, 6 = Saturday)."

      - name: order_hour_of_day
        data_type: int64
        description: "Hour of the day (0-23) when the order was placed."

      - name: days_since_prior_order
        data_type: numeric
        description: "Number of days since the user's prior order."

  - name: fact_orders
    description: "Fact table that stores aggregated information about each order, including total products ordered and the number of reordered products."
    columns:
      - name: order_id
        data_type: int64
        description: "Unique identifier for each order."

      - name: user_id
        data_type: int64
        description: "Unique identifier for the user who placed the order."

      - name: order_dow
        data_type: int64
        description: "Day of the week when the order was placed (0 = Sunday, 6 = Saturday)."

      - name: order_hour_of_day
        data_type: int64
        description: "Hour of the day (0-23) when the order was placed."

      - name: days_since_prior_order
        data_type: numeric
        description: "Number of days since the user's prior order."

      - name: total_products
        data_type: int64
        description: "Total number of products ordered in the transaction."

      - name: total_reordered_products
        data_type: int64
        description: "Total number of reordered products in the transaction."

  - name: dim_departments
    description: "Dimension table containing department data, mapping department names to unique identifiers."
    columns:
      - name: department_id
        data_type: int64
        description: "Unique identifier for each department."

      - name: department
        data_type: string
        description: "Name of the department."

  - name: dim_products
    description: "Dimension table containing product data, mapping product names to unique identifiers, along with references to aisle and department."
    columns:
      - name: product_id
        data_type: int64
        description: "Unique identifier for each product."

      - name: product_name
        data_type: string
        description: "The name of the product."

      - name: aisle_id
        data_type: int64
        description: "Unique identifier for the aisle where the product is located."

      - name: department_id
        data_type: int64
        description: "Unique identifier for the department where the product belongs."
